spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/file_upload
    username: aman
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  batch:
    jdbc:
      initialize-schema: always   # This is the correct property path
    job:
      enabled: false

server:
  port: 9090